# Generated by Django 5.2 on 2025-05-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='total_rating',
        ),
    ]
