# Generated by Django 5.2 on 2025-05-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_event_total_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
