# Generated by Django 5.2 on 2025-05-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comment_event'),
        ('app', '0003_event_total_rating'),
    ]

    operations = [
    ]
