# Generated by Django 5.2 on 2025-04-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_date_event_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
