# Generated by Django 5.2 on 2025-05-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_premium_alter_event_id_ticket_refundrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aceptado'), ('rejected', 'Rechazado')], default='pending', max_length=20),
        ),
    ]
