# Generated by Django 5.2 on 2025-05-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ticket_refundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='Evento Premium'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='policy_30_days',
            field=models.BooleanField(default=False, verbose_name='Extensión de 30 días (Premium)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
