# Generated by Django 5.2 on 2025-05-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='app.event'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
