# Generated by Django 5.2 on 2025-05-28 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20250527_1643'),
        ('app', '0006_remove_user_favorites_favorito_user_favoritos'),
    ]

    operations = [
    ]
