# Generated by Django 5.2 on 2025-05-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20250528_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='available_tickets',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('canceledo', 'Cancelado'), ('reprogramado', 'Reprogramado'), ('agotado', 'Agotado'), ('finalizado', 'Finalizado')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
