# Generated by Django 5.2 on 2025-05-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_event_status_event_tickets_sold_alter_venue_capacity'),
        ('app', '0008_remove_event_available_tickets_event_status_and_more'),
    ]

    operations = [
    ]
