# Generated by Django 5.2.2 on 2025-06-10 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_ticket_quantity_notification'),
        ('app', '0011_alter_event_status'),
    ]

    operations = [
    ]
