name: cd

on:
    push:
        branches:
            - main # Se ejecuta solo cuando haces push a la rama main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Extract metadata (tags and labels)
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ secrets.DOCKERHUB_USERNAME }}/eventhub
                  tags: |
                      type=raw,value=latest
                  labels: |
                      org.opencontainers.image.title=EventHub

            - name: Build and push Docker image
              id: build
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

            - name: Trigger Render Deploy Hook
              run: curl -X GET ${{ secrets.RENDER_HOOK }}
              env:
                  RENDER_HOOK: ${{ secrets.RENDER_HOOK }}
